# Generated by Django 5.0.1 on 2024-01-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collisiondetection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obstacledetectionevent",
            name="final",
            field=models.TextField(blank=True, null=True),
        ),
    ]
