# Generated by Django 5.0.1 on 2024-01-23 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collisiondetection", "0002_obstacledetectionevent_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obstacledetectionevent",
            name="final",
        ),
    ]
